# Global 全局配置

appName = "GiNana"

version = "1.0.0"

configIsLocal = true

configPath = "../configs"

cacheExpire = "24h"

# ginMode: release, debug
ginMode = "debug"

enableGzip = true

enableTemplate = false

# ../views
viewsPath = ""

# static:../static static2:../static2
staticDir = ""
